language: minimal
sudo: false

addons:
    apt_packages:
    - lib32stdc++6

branches:
  only:
  - master
  - dev

env:
  global:
    - secure: "LxPXGrnomUiW/mcGI5vbBvQvppf9m2tMoasodkjWur1n9uc0pl03l5C2r5eBKz+kkpI3zWnzaVMiCNBRxqbOHMa21nIdM5JBY0/6P8tcQURP8k5QeSpTAw2pF6x8bf7JIBAHkZmRFNMEnrik+yQ5wrFQiB7GgRmRE/DFBnW4VU++L4JFrXBkkTEvWr7zIi42SB/OLzxqLcMwOZHI9uh0mF55I913YV5EhGiXhzZHu8ZI7onEvWfHYdKJ2IWwFebeWx6Uplzv6ykQ7rPSs9R901PMLK+nZuOsPmmvt/sF8Vxh2ERZLt2ltCEowQBX8iC3Q5vlR26QH3wrwq0Fm2QAUQbgoz/+TVMwLyKApPSrhWd/bdcVutA6P/RjPHcg4d/XqYolTsHvd+mDit+NssFz4TL1qNjW19e9fBEUPR9Q5i0yivioAnd4+A+oUE9k2aXlJlpu0rSqZek/d27J3Xt3h5rweHLKjd5IxwHhUlNqFXftc8YJNfc6LrSqdgQjtpT34qEeuWAKsZBAxm1ynB8P9fNF8A+DW+UpPH6M4NdbhV1xEu2T9mQ0u1Dv0Rn/21AyQKkKyXIglFMFSIbzyxGOUwdMoVVfsK2vEk1VUfyE94ZDDsT6cCDFrujphk9o5Sm/dtjhn+qawiP8GUnLRMvgFYokzJTRwqM98fvEZ7knoXc="
    - secure: "JH25r0Gg0TsD9cmUKO6loC4+aHgBCT+tBkCbg3sgC/6CLBI0BSjFiYjkLvxNdILgqM5GQPEOZit8ESzjvod8GGxDy7M2rWVTerWRGbzfl5AVHai9+ZQ1rjx53JhgpbDFSqpcBJAjKvRZNiGAfQvpK/v3C+XaROZclPbDrfOCvpFIagYI8aSK7mSD1Z0KBWUlgN9UlhfhUBTAb28oOJNyZanYWSJTv1vSnyQ2atPNZ72PgCk/vQ8yFUlbcuCA1BQcg6VR28SGc9VNCCmroMpAvZBujEwNp+oIZ7z0cMyPEtinREd+GGfwe643aA2VOp7LTJHHKk44O7mL+yIaz7KMvsNWnmXdh2ZmHLKVA1To6IqpnjQLasvAVVM2FIAinO5JhRD41yMHQ/Dgn+GTeSL7jUq7PGL/5U4Bjyeu63rUJu+47E8W+ZttIk7vdrTznE3YUjz1J4mJ00UZOX8q0fhwBMQ6GDF32qwKCM4ltTz+axa4YkpSl6NFcPlaPE880GjzpF8nEynER4KQaU+gnR4S+L0F4yyWk7G/sbjxDIyskohn8gud0YJNUU8o1Zig3FVj3O3S1c6Hv5p4DjQMzX331X1obiA2m2wI499V+wV7xr7JVL65SmJ6Y8EtJaBA8D4Z3k66S+c/nZzyJk0HQI8rfJXicazgj9ecmSLu8qxxku8="

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^dev|master$

before_script:
  # SM
  - wget "https://sourcemod.net/latest.php?os=linux&version=1.9" -O /tmp/sourcemod.tar.gz
  - mkdir ~/sm && cd ~/sm
  - tar xzf /tmp/sourcemod.tar.gz addons/sourcemod/scripting
  - PATH+=:$PWD/addons/sourcemod/scripting
  # SM Builder
  - git clone "https://github.com/splewis/sm-builder" ~/sm-builder
  - cd ~/sm-builder
  - pip install --user -r requirements.txt
  - python setup.py install --prefix=~/.local

  - cd $TRAVIS_BUILD_DIR

script:
  - smbuilder --flags " -i=addons/sourcemod/scripting/include"
